### ISSUE TITLE
.a.i.SimpleAsyncUncaughtExceptionHandler occurred invoking async method

### ISSUE THREAD

**Issue by douginoz** [JasonHHouse/Gaps#105]
App stop searching after encountering `Unexpected exception occurred invoking async method: public void com.jasonhhouse.gaps.service.GapsSearchService.run()`

**To Reproduce**
1. Stop and delete existing docker
2. $ docker pull housewrecker/gaps
3. $ docker run -d -p 8484:8484 --name mygaps --expose 32400 housewrecker/gaps:latest
4. Follow prompts to insert MovieDB API key and Plex config
5. Gaps shows my existing 7 movie libraries
6. Select 'Movies' (which is my largest) then click 'Next'
7. Gaps commences searching
8. After ~1500 movies / 34% done, the log shows error.  Gaps stops/hangs on searches at that point.

**Expected behavior**
It should reach 100% completion

**Screenshots**
Gaps_crash_douginoz_20200109_screenshot

**Desktop (please complete the following information):**
 - OS: kubuntu 19.04
 - Browser Firefox v72
 - Gaps Version 0.1.4 (also same error in 0.1.0)

**Additional context**
Library has 4300 movies
Error occurs even after rebuilding plex library db as per https://support.plex.tv/articles/201100678-repair-a-corrupt-database/  (no errors found).

I suspect there's a specific movie that it's failing on.  I need a debug version or runtime option to have it log each movie it is about to work on.
[Gaps_crash_douginoz_20200109_applog.txt](https://github.com/JasonHHouse/Gaps/files/4043625/Gaps_crash_douginoz_20200109_applog.txt)
![Gaps_crash_douginoz_20200109_screenshot](https://user-images.githubusercontent.com/1946361/72120365-99222f80-330c-11ea-9c56-a4c846b04e3d.png)

**Comment by douginoz** [comment]
I just tried version 0.1.6 and now it fails immediately with the exact same error.  In other words, it shows:
2020-01-10 04:20:55.178  INFO 1 --- [         Gaps-2] c.j.gaps.service.GapsSearchService       : Searching for Movie Collections...
2020-01-10 04:20:55.178  INFO 1 --- [         Gaps-2] c.j.gaps.service.GapsSearchService       : 0% Complete. Processed 0 files of 4298. 
2020-01-10 04:20:56.650 ERROR 1 --- [         Gaps-2] .a.i.SimpleAsyncUncaughtExceptionHandler : Unexpected exception occurred invoking async method: public void com.jasonhhouse.gaps.service.GapsSearchService.run()

**Comment by JasonHHouse** [comment]
I haven't started work on your issue yet. I'm only one guy. :)

**Comment by douginoz** [comment]
I only love one guy! ;)

**Comment by JasonHHouse** [comment]
Can you try `v0.2.1-alpha-no-ssl` or `v0.2.1-alpha` please?

**Comment by douginoz** [comment]
So far so good.  I saw what looked like the same stack dump when it started but it scrolled out of my term's buffer so I don't have a copy.  Is there a way to get a full history via the 'docker logs -f mygaps' command or otherwise?
Regardless, clearly something's changed in this alpha release.  I tried the v0.2.0 release yesterday but had the same problem as v0.1.6 etc.  This time, it's progressing nicely.
Will post another update soon.

**Comment by douginoz** [comment]
It completed successfully.  The web ui said that there were 327 suggestions but when I imported the RSS feed into radarr, it listed 207.  I assume radarr found that 120 movies were already in my collection, possibly.  Not sure.  Not a biggie.
I re-rean gaps hoping to see an/the error but there wasn't one.   What I thought was a stack dump wasn't.
So this v02.1 seems to be working.  
Many thanks for fixing this!

**Comment by JasonHHouse** [comment]
Glad to see it's working. I'll look into the number difference between radar and gaps.
