### ISSUE TITLE
Accents encoding

### ISSUE THREAD

**Issue by Galiwyx** [JasonHHouse/Gaps#106]
Hello,

In the 0.2.0 release, accents are not encoded in the "Recommended section" 

`AstÃ©rix & ObÃ©lix (Animation) `

Besides, the Recommended section is named "Owned Movies" instead of Recommended. And When I click on the "Owned Movies" it displays the "Missing Movies" Page.

![image](https://user-images.githubusercontent.com/206181/72482438-fed75580-37fd-11ea-8f8e-864501118353.png)

![image](https://user-images.githubusercontent.com/206181/72482451-0696fa00-37fe-11ea-8c20-6e39bcb124b4.png)

**Comment by JasonHHouse** [comment]
v0.2.0 is not a production release. It's still under development and testing.

If you want to use a production-ready version, target latest.
