### ISSUE TITLE
Allow http connections instead of only https

### ISSUE THREAD

**Issue by Ablecken** [JasonHHouse/Gaps#107]
**Is your feature request related to a problem? Please describe.**
I wanted to add this to the [PGBlitz ](https://github.com/PGBlitz/PGBlitz.com/wiki) setup I have.  It uses Traefik to allow all the different applications/containers to talk to each other.  I have already [added a yml](https://github.com/Ablecken/Apps-Community/blob/gaps/apps/gaps.yml) and I have it running alright, but it is not accessible outside nor is it accessible from the other containers due to an SSL cert error.  I think it might be related to this ticket:  [https://github.com/JasonHHouse/Gaps/issues/59](https://github.com/JasonHHouse/Gaps/issues/59)

**Describe the solution you'd like**
Just allow it to respond via http on some other port, maybe 8483 or something.  That would allow it to be added to the PGBlitz community rep easily and would open it up to a lot more users.

**Describe alternatives you've considered**
I can access it just fine running another container that has access to it in the network by accepting the SSL cert in the browser.  However, most of the other applications cannot/will not do that.

**Comment by Ablecken** [comment]
So I noticed the no-ssl containers that you have up, but they don't seem to want to work.  I don't know much about springboard, but in [this commit](https://github.com/JasonHHouse/Gaps/commit/f7d932c7b0b3e2f5e74395c9c60369b1e70eb98e#diff-0d06814005b0c44081469a16e2dfd4da) you added what appears to be the profiles, commented out.  [In the next edit](https://github.com/JasonHHouse/Gaps/commit/dfb84930a61bc5bed2f41fbf28b8d3fde1511976#diff-0d06814005b0c44081469a16e2dfd4da), they were removed.  Do you know the correct commands to get your no-ssl images working?

**Comment by JasonHHouse** [comment]
I just tested the no-ssl and it worked. What's in your docker log? What URL are you using? What OS are you running on?

**Comment by Ablecken** [comment]
I was eventually able to get the no-ssl image working, it was an unrelated issue.  However, I need it to be able to respond on a http request.  I assumed the no-ssl would handle that, but I still get this error when going to the page:

```
Bad Request
This combination of host and port requires TLS.
```

This is what I get even in the docker image running in lynx.  I'll be the first to admit that I am not that great at either docker or Traefik, but I would assume the no-ssl would allow us to connect via http.  I have verified that the image is `housewrecker/gaps:latest-no-ssl`

**Comment by Ablecken** [comment]
I think I figured it out, and it's working properly.  Looks like I had the correct image, but the wrong entrypoint setup.  Probably having to do with how I was testing.

Still learning!  Thanks for your time and for this awesome product :)

**Comment by JasonHHouse** [comment]
Glad you go it figured out and happy you're enjoying it!
