### ISSUE TITLE
Re-search after initial search of library

### ISSUE THREAD

**Issue by TheChrisTech** [JasonHHouse/gaps#120]
**Describe the bug**
After the initial search of the Plex Library is complete, attempting to click "Search" again in the library won't kick off a new search.

Current Library: 760
Initial Search: 708

Clicking _Search_ throws the following lines in the docker logs:

> 2020-05-26 09:12:16.303 INFO 1 --- [nio-8484-exec-3] c.j.g.c.PlexMovieListController : getPlexMovies( 2997a2dfc3a9e6a2feabe1724f79337582dc9525, 1 )
> 2020-05-26 09:12:16.304 INFO 1 --- [nio-8484-exec-3] com.jasonhhouse.gaps.service.IoService : readOwnedMovies( 2997a2dfc3a9e6a2feabe1724f79337582dc9525, 1 )
> 2020-05-26 09:12:16.317 INFO 1 --- [nio-8484-exec-3] com.jasonhhouse.gaps.service.IoService : writeOwnedMoviesToFile()

There's nothing more after this.

Is there a debug mode so I can see it processing each movie or a way to see if it's actually doing anything more? Also, is there a local log that this docker writes more info to?

**Environment**
Running both Plex and Gaps in dockers on Unraid 6.8.3.

**Comment by JasonHHouse** [comment]
Set for v0.4.1

**Comment by JasonHHouse** [comment]
Fixed, pull latest or v0.4.1
