### ISSUE TITLE
Unable to access Web UI via nginx reverse proxy

### ISSUE THREAD

**Issue by ImjuzCY** [JasonHHouse/gaps#136]
**Describe the bug**
When accessing the web UI via nginx reverse proxy, I get HTTP Status 400 - Bad Request

**To Reproduce**
1. Set up docker container with latest image
2. Set up nginx reverse proxy
3. Access via reverse proxy
4. Get error HTTP Status 400 - Bad Request

**Expected behavior**
Access web UI as usual 

**Desktop (please complete the following information):**
 - OS: Docker: Ubuntu, Browser: Windows
 - Browser: Chrome
 - Gaps Version: 0.4.8

**Additional context**
Accessing the web UI via http on ip:8484 work fine, but when routed through nginx gets error. I looked for similar issues on github, but the only result returned is not the same as this I guess. I'm not getting SSL error.

**Comment by JasonHHouse** [comment]
If the UI works via localhost, this sounds like an nginx/Windows issue. Are you exposing the correct ports?

**Comment by Knoxie** [comment]
I have nginx on my machine I can test with. Which version of gaps are you using SSL or non?

**Comment by ImjuzCY** [comment]
> If the UI works via localhost, this sounds like an nginx/Windows issue. Are you exposing the correct ports?

Do I have to expose any ports if I'm using docker compose and the nginx and gaps containers are all connected to the same docker network, so it should suffice that in my nginx proxy configuration that I use gaps:8484 as upstream server even without exposing any ports on the gaps container. At least that has been the case for a dozen of other containers that I have set up with the same fashion.



> I have nginx on my machine I can test with. Which version of gaps are you using SSL or non?

I'm using the SSL version (latest instead of latest-no-ssl), but as upstream server in nginx configuration I'm using port 8484, through which I did not receive any browser warning about self signed certs when I connect via ip:port, so I assume it's a non SSL port?

**Comment by ImjuzCY** [comment]
I think I might have found the problem. I should've checked the log first. It's written there the character [_] is never valid in a hostname. And I changed the upstream name from gaps_backend to gapsbackend (removed the underscore), and it works now. I don't understand why this should be a problem though, as I have used underscores in other containers' upstream name and have never had any problems.
