### ISSUE TITLE
[Feature Request] Discord notifcation

### ISSUE THREAD

**Issue by rg9400** [JasonHHouse/gaps#147]
**Is your feature request related to a problem? Please describe.**
I use Discord notifications for all my services because they can be relatively unintrusive compared to emails or Telegram; however, I couldn't get the Slack notification to work with my Discord webhook. For some other services, it's usually enough to tack on `/slack` at the end of the Discord webhook URL, but GAPS was throwing errors when testing that.

**Describe the solution you'd like**
Either native support for Discord, or modifying the Slack notification to work for Discord as well.  The former is better just because Discord is more popular amount non-enterprise users (main audience of GAPS)

**Describe alternatives you've considered**
Not getting any notifications since the feature didn't exist until today. Excellent feature by the way!

**Comment by JasonHHouse** [comment]
I agree I think the best option is to just add Discord directly. I can put that at the top of the list for the next notification agent. Glad you like the addition of notifications though!

**Comment by BEisem** [comment]
I would like to add my voice to this request! I went through exactly the same thing as the OP ... added /slack to the end of the webhook which usually works, but it does not in this case. Native Discord support would be fantastic!

**Comment by Backslashh** [comment]
Another vote for this please. 👍
