### ISSUE TITLE
Create a scheduler to automatically run in docker through spring boot

### ISSUE THREAD

**Issue by JasonHHouse** [JasonHHouse/gaps#15]
Need to configure the app when running in docker to automatically run through a scheduler to keep up to date.

**Comment by Geek16432** [comment]
Yes please, possibly have the interval set in the configuration pages per LIbrary?

I know my movies change about once a week, but TV shows are multiple times a day.

**Comment by CorneliousJD** [comment]
I also think we need a way to schedule re-scans at the very least so it updates the list on a schedule. My docker container can be up and open for weeks or months on end and a way to schedule re-scans would be great. Then the RSS will update, and Radarr will update it from there.

@JasonHHouse  is this soemthing that's already implemented and I'm just not seeing it? I tried looking in config files but didn't see any way references to automated/scheduled runs.

**Comment by JasonHHouse** [comment]
It's not yet. I can work this one next. What degree of configuration for how often Gaps run are you looking for?
- 1 Day
- 1 Week
- 2 Weeks
- 1 Month

**Comment by CorneliousJD** [comment]
> It's not yet. I can work this one next. What degree of configuration for how often Gaps run are you looking for?
> 
> * 1 Day
> * 1 Week
> * 2 Weeks
> * 1 Month

I would personally probably just let it auto-refresh once a day because why not, but I think those options would probably suffice for most -- if someone has a small library, once a day is good, medium size they may want every 1 or 2 weeks (though they would probably want to configure the day), etc.

Thanks for the consideration!

**Comment by JasonHHouse** [comment]
Cool, I'll put this work to the top of the list. It shouldn't be too long to get it done.

**Comment by JasonHHouse** [comment]
Complete via 0.5.0+
