### ISSUE TITLE
GAPS Reports Incorrectly

### ISSUE THREAD

**Issue by angrycuban13** [JasonHHouse/gaps#168]
**Describe the bug**
I tried to make the title TL;DR because by the time I finished typing it, it looked like a bug report.

As I was looking through the import list on Radarr, I noticed that GAPS was suggesting some really odd movies.

For instance it says I'm missing all the movies from ["Spenser Collection" ](https://www.themoviedb.org/collection/681327-spenser-collection) but I have no movies from that collection on my library. I think it sees ["Spenser: Confidential"](https://www.themoviedb.org/movie/581600-spenser-confidential) and mistakenly thinks there is a whole collection missing.

Additionally, it is also reporting that I'm missing movies from a collection and under "Owned", it shows I don't have any of those movies, when in fact I do. So sort of similar to the issue in the first paragraph, but it is the opposite. I do have movies for that collection and it says I'm missing them.

**Screenshots**
Here is the a screenshot of what I described on the first paragraph.
![](https://i.imgur.com/6i53G7x.png)

Here is a screenshot of what I described on the second paragraph. As you can see I do have that movie.
![](https://i.imgur.com/gDz464r.png)
![](https://i.imgur.com/XPeWSMi.png)

**Desktop (please complete the following information):**
 - OS: Docker latest Image
 - Browser: Firefox 80.0.1
 - Gaps Version 0.7.5

**Comment by JasonHHouse** [comment]
Please attach the full logs from Gaps.

**Comment by angrycuban13** [comment]
https://pastebin.com/YMEsV1qg

Here are the docker logs. If there are other specific logs you want me to get, please let me know where to find them in the container.

Thanks!

**Comment by JasonHHouse** [comment]
Run a search then give me the logs. This only has the RSS output. Not the information of your owned movies vs what Gaps found.

**Comment by angrycuban13** [comment]
It looks like I'm hitting size limits in the different text bins. I've attached a .txt file on here.
[GAPS Logs.txt](https://github.com/JasonHHouse/gaps/files/5212916/GAPS.Logs.txt)

**Comment by JasonHHouse** [comment]
I'm not sure how this happened but 'Marvel One-Shot Item 47' is saying it has a collection when it doesn't. The collection then links to the Spenser Collection. I recommend going to configuration > Advanced > Delete All Stored Data > Delete. Then rescan plex and rerun gaps. It looks like the Plex movie Gaps found is incorrect. So if this doesn't work, you can try sending over the json files for Plex. They're in /usr/dev. It's either Gaps parsing the Plex XML incorrectly or Plex matched incorrectly.

**Comment by angrycuban13** [comment]
That seems to have fixed it. Thanks for your time.
