### ISSUE TITLE
[Feature Request] Add compiled .jar to releases

### ISSUE THREAD

**Issue by cadatoiva** [JasonHHouse/gaps#169]
I recently found your utility and would like to use it on my server. However, I use FreeBSD, which is a *NIX/POSIX system that does not support docker in favor of it's older and more secure native solution called jails.

The way your current releases are listed means that in order for me to use your utility on my server I need to either download the windows installer and extract the .jar file, install the docker container on a different OS and extract the .jar, or compile from source myself. It would be appreciated if the precompiled .jar was available as a release asset on your new versions so I can download it directly to my system without any extra hassle.

**Comment by JasonHHouse** [comment]
Added to the 0.7.5 release and will do going forward.

https://github.com/JasonHHouse/gaps/releases/tag/v0.7.5

**Comment by cadatoiva** [comment]
Thanks!
