### ISSUE TITLE
Synology NAS Install Drive Mapping Unclear

### ISSUE THREAD

**Issue by BayIsland757** [JasonHHouse/gaps#175]
On synology NAS under docker, typically you map a local volume to an expected path.  What is that path required by gaps?  (e.g. is it /config or is it /usr/data ?)

Are there any other environment variables that need to be set within the synology docker console?

On my initial run it does not show movie posters nor does it retain configuration files.

**Comment by JasonHHouse** [comment]
It's `/usr/data` for the mount. The port mapping would be `-p 8484:8484` 

The posters issue is a bug I'm tracking and working [here](https://github.com/JasonHHouse/gaps/issues/170).

**Comment by BayIsland757** [comment]
Thanks!  That fixed the persistence issue between runs.  Will standby on the poster issue................
