### ISSUE TITLE
Collapsible Notifications until Enabled

### ISSUE THREAD

**Issue by ePHDiSK** [JasonHHouse/gaps#178]
**Is your feature request related to a problem? Please describe.**
Notifications Section is a very very long scroll.  Most people would only use 1 to 2 integrations.  This is a very minor inconvenience and purely a visual request

**Describe the solution you'd like**
Notifications Section: Have all integrations collapsed unless you enable them.  

**Describe alternatives you've considered**
Ctrl F for the integration app I am looking for

**Additional context**
Very amazing work and I really appreciate this docker and all the effort put in to it.  Thank you!

**Comment by JasonHHouse** [comment]
I can do that. That's a pretty easy fix. Thanks for the idea.
