### ISSUE TITLE
Unable to find image 'housewrecker/gaps:latest' locally

### ISSUE THREAD

**Issue by Bboy486** [JasonHHouse/gaps#181]
$ sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v 
/{localFolder}/gaps:/usr/data housewrecker/gaps:latest

Unable to find image 'housewrecker/gaps:latest' locally
latest: Pulling from housewrecker/gaps
docker: no matching manifest for linux/arm/v7 in the manifest list entries.
See 'docker run --help'.

**Comment by JasonHHouse** [comment]
You need to use ARM versions of docker not x86.

Try
`docker pull housewrecker/gaps:arm-latest`
or
`docker pull housewrecker/gaps:armhf-latest`

**Comment by Bboy486** [comment]
I did use the arm for the first step
docker pull housewrecker/gaps:arm-latest
so should I change  
sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v
/{localFolder}/gaps:/usr/data housewrecker/gaps:latest to 

sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:arm-latest
?

**Comment by JasonHHouse** [comment]
Yes, the run command previously would be pulling x86 and not arm. Was this in the documentation? I can make a fix if it's wrong

**Comment by Bboy486** [comment]
It says ​docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:latest

So that was what I initially ran. 


Last login: Sun Sep 27 21:41:41 2020 from 192.168.1.97
pi@raspberrypi:~ $ sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:arm-latest
docker: Error response from daemon: Conflict. The container name "/mygaps" is already in use by container "acb3ec22b9e9be98514726a7f273f271221ce683bc304e4a0e5fe55045677565". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
pi@raspberrypi:~ $ sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:arm
Unable to find image 'housewrecker/gaps:arm' locally
docker: Error response from daemon: manifest for housewrecker/gaps:arm not found: manifest unknown: manifest unknown.
See 'docker run --help'.
pi@raspberrypi:~ $ sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:armhf
Unable to find image 'housewrecker/gaps:armhf' locally
docker: Error response from daemon: manifest for housewrecker/gaps:armhf not found: manifest unknown: manifest unknown.
See 'docker run --help'.
pi@raspberrypi:~ $ sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:armhf-latest
docker: Error response from daemon: Conflict. The container name "/mygaps" is already in use by container "acb3ec22b9e9be98514726a7f273f271221ce683bc304e4a0e5fe55045677565". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
pi@raspberrypi:~ $ sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:arm-latest
docker: Error response from daemon: Conflict. The container name "/mygaps" is already in use by container "acb3ec22b9e9be98514726a7f273f271221ce683bc304e4a0e5fe55045677565". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.


When I go to localhost gaps doesn't load. Likely my issue

**Comment by JasonHHouse** [comment]
The documentation is assuming x86. I'll update that to account for each build arch. The error you have there is trying to run a container that has the same name as one already in your local docker. Just make sure to remove the containers, if you're switching around. Once you remove the old container, try with the arm run command you posted above.

**Comment by Bboy486** [comment]
Sorry I have not used docker before. If you can just let me know the next steps I would appreciate it. Would I run:

docker system prune
then rerun the arm instructions?

**Comment by JasonHHouse** [comment]
If gaps is stopped, `docker system prune -a` will remove everything. Then you can run `sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:arm-latest`

If that doesn't work, you can run `docker ps` and copy the id of gaps. Then run `docker rm {id}`. Then you can run `sudo docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:arm-latest`

**Comment by Bboy486** [comment]
thanks. I was able to remove docker but when I re-run it (no errors this time) the localhost, 127 or IP of the Pi:8484 does not load. I tried both on the pi and on another laptop.

**Comment by g4m3r7ag** [comment]
Slightly related, it looks like v0.8.1 was only pushed to dockerhub for arm, the regular amd64 image is still v0.8.0. Not sure if this is by design or not, just noticed I couldn't update my container. The latest tag on dockerhub still shows last updated 13 days ago.

**Comment by JasonHHouse** [comment]
@Bboy486 Please post the docker log

@g4m3r7ag Thanks for that catch, there was an error in a couple of docker files. They are updated and pushed now.

**Comment by Bboy486** [comment]
sudo docker ps -a

eead1ca01904        housewrecker/gaps:arm-latest   "/init /bin/sh -c ./…"   2 days ago          Exited (1) 2 days ago                       mygaps

 sudo docker logs --follow eead1ca01904
standard_init_linux.go:211: exec user process caused "exec format err                  or"

sudo docker logs --tail 100  eead1ca01904
standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by JasonHHouse** [comment]
Your using arm v8 and your raspberry doesn't support that. I have a raspberry release version. The wiki now has write ups. The docker architecture matters as the containers only run on specific architectures.

**Comment by Bboy486** [comment]
I have a raspberry pi 4. Ran Armv7 and it worked. Thanks for all your help.
