### ISSUE TITLE
Instructions for running on a raspberry Pi

### ISSUE THREAD

**Issue by Bacchusm** [JasonHHouse/gaps#190]
Can you included instructions for getting this to run on a raspberry pi, please

Thanks in advance

Bacchus

**Comment by JasonHHouse** [comment]
You have a few options. You can run locally or with docker. I would recommend docker, it's much easier to maintain. And learning and setup is simple. The Gaps wiki has information in raspberry docker setup. I have a specific container you will use.

**Comment by julio8a** [comment]
Can you provide the URL to the Wiki? is it this one?
https://github.com/JasonHHouse/gaps/wiki/Running-Gaps-in-Docker-on-ARM-v8

**Comment by julio8a** [comment]
I tried these two images, but none worked.

housewrecker/gaps:raspbian-latest
```
/bin/sh: ./start.sh: not found
```

housewrecker/gaps:arm-latest
```
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by julio8a** [comment]
Nevermind, got it working with `housewrecker/gaps:armhf-latest`

**Comment by JasonHHouse** [comment]
Sounds good.
