### ISSUE TITLE
Issue with Non-English Characters

### ISSUE THREAD

**Issue by MatthewT1** [JasonHHouse/Gaps#20]
Thanks for an awesome project - after figuring out the All Movie URL everything works well, and I'm able to redirect StdOut to get the output easily. 

We have a few non-English collections in our library though, and it looks like Gaps is having a hard time with them - we're getting question marks instead of names in the output: 

> 
?????? ??? ????????? ????? - ? (2012)  ---  collection='Gangs of Wasseypur Collection'
?????? ??? ????????? ????? - ? (2012)  ---  collection='Gangs of Wasseypur Collection'
?????????? (2003)  ---  collection='Buppah Ratree'
?????????? 3.1 (2009)  ---  collection='Buppah Ratree'
?????????? 3.2 (2009)  ---  collection='Buppah Ratree'
?????????? ??? 2 (2005)  ---  collection='Buppah Ratree'
?????????????? (2016)  ---  collection='Buppah Ratree'
????? (2004)  ---  collection='Ghost in the Shell Collection'
?????????? (1962)  ---  collection='Godzilla (Showa) Collection'
??? (1954)  ---  collection='Godzilla (Showa) Collection'
??? ????????? (2004)  ---  collection='Godzilla (Millennium) Collection'
???vs?????? (1991)  ---  collection='Godzilla (Heisei) Collection'
???vs??????? (1994)  ---  collection='Godzilla (Heisei) Collection'
???vs????? (1989)  ---  collection='Godzilla (Heisei) Collection'
???vs????? (1993)  ---  collection='Godzilla (Heisei) Collection'
???vs??? (1992)  ---  collection='Godzilla (Heisei) Collection'
???×????? (2002)  ---  collection='Godzilla (Millennium) Collection'
???×????? G???? (2000)  ---  collection='Godzilla (Millennium) Collection'
???×???×????????SOS (2003)  ---  collection='Godzilla (Millennium) Collection'
?????????????????? (1966)  ---  collection='Godzilla (Showa) Collection'
???????????????????? (2001)  ---  collection='Godzilla (Millennium) Collection'
??????? (1971)  ---  collection='Godzilla (Showa) Collection'
????????? (1974)  ---  collection='Godzilla (Showa) Collection'
??????? ?????? (2017)  ---  collection='Resident Evil: Biohazard'
??????? (1964)  ---  collection='Godzilla (Showa) Collection'
???????????? (1964)  ---  collection='Godzilla (Showa) Collection'
???? (2000)  ---  collection='Crouching Tiger, Hidden Dragon Collection'
?????? ???????? (1972)  ---  collection='Godzilla (Showa) Collection'
????? (1968)  ---  collection='Godzilla (Showa) Collection'
????? 2.0 (2008)  ---  collection='Ghost in the Shell Collection'
?? (1978)  ---  collection='Drunken Master Collection'
??III (1994)  ---  collection='Drunken Master Collection'
??? (1994)  ---  collection='Drunken Master Collection'
???? ?? (2001)  ---  collection='My Sassy Girl Collection'
???? ?? 2 (2016)  ---  collection='My Sassy Girl Collection'

Just wondering if there's a possible fix to have it print the English title?

**Comment by JasonHHouse** [comment]
Can you send me a few of the movies in the collections so I can see what's going on? It sounds like a Unicode issue.

**Comment by JasonHHouse** [comment]
Updated Gaps to return results in English for foreign movies. This will fix that issue.
