### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by SteffanCline** [JasonHHouse/gaps#202]
Is there something I am missing where I can set the paths? On macOS Catalina, users are not permitted to write to /usr like that without disabling features. Is it possible to set a flag to set a different path than /usr/data? I plan on making a launchd file for it and would like to try and set Gaps to store it's files in the usual places for macOS like ~/Library/Application Support/Gaps

**Comment by SteffanCline** [comment]
Looking around while waiting, I saw reference to https://github.com/JasonHHouse/gaps/wiki/Running-in-Linux-Mac-without-Docker but that seems overkill. Can't you add a flag to the source for data-dir and log-dir or something like that? I'll provide the launchd file for macOS you can include in your distro when I get this going.

**Comment by JasonHHouse** [comment]
I don't know what a flag to the source means. It's just a configuration file with a couple of changes. If you want to improve it, feel free to make a PR.

**Comment by SteffanCline** [comment]
Currently you define the path to the .db file in a config file. While that works, when daemonizing the process it will be easier if if the config file can be omitted and the paths defined in a command line argument. 

I'm thinking something in the line of 
java -Dspring.config.home=/path/to/binary -Dspring.config.data=/path/to/db/file -jar gaps.jar

I have a working launchd file I'm working on and will provide it when done so you can include it in your distro for macOS users.

**Comment by JasonHHouse** [comment]
Gaps is firstly a Docker application. Secondary support on Mac is recommended this way. https://github.com/JasonHHouse/gaps/wiki/Running-in-Linux-Mac-without-Docker

If you want to improve it, feel free to make a PR.

**Comment by SteffanCline** [comment]
Please update your wiki page for mac to include this:

In /Applications/GapsAsJar/application-custom.yml change the following:
<pre>url: jdbc:sqlite:/Applications/GapsAsJar/data/gaps.db #Change to folder that gaps has permission to read, write, and delete in.</pre>
<pre>storageFolder: /Applications/GapsAsJar/data #Change to folder that gaps has permission to read, write, and delete in.</pre>

in <pre>~/Library/LaunchAgents</pre> create the file: <pre>org.user.gaps.plist</pre> with the following content:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
	<key>EnvironmentVariables</key>
    	<dict>
        	<key>PATH</key>
        	<string>/Library/Java/Home/bin:$PATH</string>
    	</dict>
		<key>WorkingDirectory</key>
    	<string>/Applications/GapsAsJar</string>
        <key>Label</key>
        <string>org.user.gaps.plist</string>
        <key>ProgramArguments</key>
          <array>
            <string>/usr/bin/java</string>
            <string>-Dspring.config.location=classpath:file:application-custom.yml</string>
            <string>-Dspring.profiles.active=custom</string>
            <string>-jar</string>
            <string>gaps.jar</string>
         </array>
        <key>RunAtLoad</key>
            <true/>
        <key>KeepAlive</key>
            <true/>
        <key>StandardErrorPath</key>
            <string>logs/gaps-launchd.log</string>
        <key>StandardOutPath</key>
            <string>logs/gaps-launchd.log</string>
    </dict>
</plist>
```

Save it then start Gaps with <pre># launchctl load org.user.gaps.plist</pre>

Launch the browser to http://localhost:8484/ and configure.

**Comment by JasonHHouse** [comment]
Updated, thanks for the help.
