### ISSUE TITLE
Running on Windows

### ISSUE THREAD

**Issue by JamieP83** [JasonHHouse/gaps#207]
**Describe the bug**
Sorry, followed the instructions and some other "issues" but cant get it to work still.

**To Reproduce**
I downloaded GAPS and JDK11 - both added into "C:Program Files"
Rebooted
ran "startOnWindows.bat" but got error below

Note:
- The documentation states to run "start.bat" however that doesnt exist, so im using "startOnWindows.bat" 
- I modifed the bat file, changed to "echo=on" to get the logs below.

**Expected behavior**
the program to run?

**Screenshots**
 
![image](https://user-images.githubusercontent.com/48566948/103889265-0a422180-50de-11eb-95a5-183184d17242.png)

![image](https://user-images.githubusercontent.com/48566948/103888117-14632080-50dc-11eb-97a3-577f2cdddd7d.png)
![image](https://user-images.githubusercontent.com/48566948/103888152-22b13c80-50dc-11eb-924e-ab351988752c.png)
![image](https://user-images.githubusercontent.com/48566948/103888172-3197ef00-50dc-11eb-87ce-a9797cdfe85e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser NA
 - Gaps Version 0.8.5

**Additional context**

PS C:\Program Files\gaps-0.8.5> .\startOnWindows.bat

C:\Program Files\gaps-0.8.5>SET s=false

C:\Program Files\gaps-0.8.5>SET l=false

C:\Program Files\gaps-0.8.5>if "" == "" goto done

C:\Program Files\gaps-0.8.5>if false == true (if false == true (
echo "Running with SSL and Login"
 call java -jar -Dspring.profiles.active=ssl gaps.jar
)  else (
echo "Running with SSL and without Login"
 call java -jar -Dspring.profiles.active=ssl-no-login gaps.jar
) )  else (if false == true (
echo "Running without SSL and with Login"
 call java -jar -Dspring.profiles.active=no-ssl gaps.jar
)  else (
echo "Running without SSL and without Login"
 call java -jar -Dspring.profiles.active=no-ssl-no-login gaps.jar
) )
"Running without SSL and without Login"
Error: Unable to access jarfile gaps.jar
PS C:\Program Files\gaps-0.8.5>

**Comment by JasonHHouse** [comment]
It looks like you checked out the source, rather than grabbing a release. https://github.com/JasonHHouse/gaps/releases/download/v0.8.5/GapsAsJar-0.8.5.zip You have folders with source, which is fine you just would have to build the code. If you extract this folder, that has the compiled jar ready to run.
