### ISSUE TITLE
Radarr cannot connect to RSS when login is enabled

### ISSUE THREAD

**Issue by ssiddiqui87** [JasonHHouse/gaps#223]
**Describe the bug**
When I try to navigate to my RSS URL (http://rss/1) when ENABLE_LOGIN is set to true, it redirects me to the login page

**To Reproduce**
1. Set ENABLE_LOGIN to true
2. Navigate to RSS URL

**Expected behavior**
Rather than being directed to the login page, the RSS feed should be displayed

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: All browsers
 - Gaps Version v0.8.10 on Docker

**Comment by JasonHHouse** [comment]
Please retest. This is fixed now.

**Comment by ssiddiqui87** [comment]
Awesome! It works now, thank you!

**Comment by ssiddiqui87** [comment]
Actually, while I can access the RSS while ENABLE_LOGIN is true, it no longer prompts me to log in and I can access the front end without authentication

**Comment by JasonHHouse** [comment]
It's using a basic login now. There's no login page anymore just a box that pops down when login is required. Can you try in incognito mode?

**Comment by ssiddiqui87** [comment]
Interestingly, even in incognito mode I didn't get a popup box however using another browser prompted it so this is all good now. Thanks again!
