### ISSUE TITLE
No Real Suggestions

### ISSUE THREAD

**Issue by Imburr** [JasonHHouse/gaps#228]
I just set this up, and connected to movie DB and plex successfully. After I scan for missing, it just lists all titles, owned, and also missing. It does not link anything, so I am missing every movie that I own. For instance I own both of these movies, but they not only list each other as missing but they miss themselves.

![image](https://user-images.githubusercontent.com/2759346/120032948-eddd4d80-bfc8-11eb-9240-3aee2a0a2bb2.png)

**Comment by JasonHHouse** [comment]
What OS are you running on? 
What version are you running?

I'll need the logs and the JSON files under /usr/data to know what's going on.

**Comment by Imburr** [comment]
This is docker build on Ubuntu 20 LTS which is running in a VM on ESXi 7.

[overseerr-2021-05-28.log](https://github.com/JasonHHouse/gaps/files/6563760/overseerr-2021-05-28.log)

[overseerr-2021-05-28.log](https://github.com/JasonHHouse/gaps/files/6563761/overseerr-2021-05-28.log)

Quick question while I have you- is it not advised to expose Overseer directly to the internet without a proxy. even if it has SSL? I ready through your proxy documentation, did not see mention of just letting the app be exposed.

**Comment by JasonHHouse** [comment]
I think there is some confusion here. I don't own or maintain Overseer. This is for Gaps.

**Comment by Imburr** [comment]
So sorry! I posted the wrong logs, I am working with a few projects now.
[GAPS.zip](https://github.com/JasonHHouse/gaps/files/6563805/GAPS.zip)

**Comment by JasonHHouse** [comment]
No worries. I'll take a look at it.

**Comment by JasonHHouse** [comment]
It looks like the issue was that IMDB and TDMB call some movie titles differently. The example would be `X2 X-Men United` vs `X2`. I added some logic to check by ID before falling back to title so that should resolve your issue. I pushed up 0.9.1. Please pull, test, and let me know if that helped.

**Comment by Imburr** [comment]
I did a pull, remove previous container, and spun up a new container. All of my data stayed, and the results are the same. I perhaps pulled it incorrectly?

```
docker pull housewrecker/gaps:latest
docker run -d -p 8484:8484 --name mygaps --expose 32400 -v /{localFolder}/gaps:/usr/data housewrecker/gaps:latest
```

**Comment by Imburr** [comment]
I think I might see whats hapenning. I have a 4K library withy Dark Pheonix (X-Men) in it, and all of my other X-Men are in a different library. So when looking at missing in 4K it doesn't see any of the other libraries. Is this intended? Is there a way to just view the whole library at once?

**Comment by JasonHHouse** [comment]
Yes. I do not have a full view, that would be a new feature to request.
