### ISSUE TITLE
Windows fails to launch

### ISSUE THREAD

**Issue by Jacob10383** [JasonHHouse/gaps#232]
Upon trying to launch, I get the error: java.sql.SQLException: path to '/usr/data/gaps.db': 'C:\usr' does not exist

I attached the entire msg displayed if it helps.
[full.txt](https://github.com/JasonHHouse/gaps/files/6569180/full.txt)

**Comment by JasonHHouse** [comment]
You'll need to use this YML file to launch, rather than the Linux/Mac version

https://github.com/JasonHHouse/gaps/blob/master/GapsWeb/src/main/resources/application-windows.yaml

Just have to change the directory's.

**Comment by Jacob10383** [comment]
How do I use the YML file to launch? As far as I know, you need docker to run them and I am using option 2 without docker.

**Comment by JasonHHouse** [comment]
The yml file and jar all need to be in the same folder. You just need to edit yours in a text editor. Find the line with `/usr/data/gaps.db` and change it to the folder your running in like `C:\users\{username}\gaps`, for example. 

Everything is packed up in the zip. https://github.com/JasonHHouse/gaps/releases/tag/v0.9.3

**Comment by Jacob10383** [comment]
Thank you. In order to get it working I had to change "/usr/data/gaps.db" like you said. However, changing it to the folder did not work, I had to change it to "C:\Users\jacob\gaps\gaps.db" for it to work. Glad it is working though, and thanks for the help. For future reference though, I am a little confused as to what the application-windows.yaml does? The only way it worked for me was by editing application.yaml. It did not matter if application-windows was present whatsoever.

**Comment by JasonHHouse** [comment]
Ah, I'm sorry. Yes, you would need the `gaps.db` at the end. I'm glad you go it working. 

Spring is supposed to look for all application.yml files including sub yaml files which can override the base application.yml. This is assuming they are both in the same folder. I'm not sure why that didn't work for you. But I'm glad it is now.
