### ISSUE TITLE
HTTP Status 404 – Not Found on Docker/Unraid

### ISSUE THREAD

**Issue by steve-spiteri** [JasonHHouse/gaps#245]
**Describe the bug**
Docker container starts but WebUI only shows the following error message:
HTTP Status 404 – Not Found

**To Reproduce**
Launch the docker container.

**Screenshots**
![image](https://user-images.githubusercontent.com/22033488/122224201-e1d70400-ce81-11eb-8e72-8752fc4de73a.png)
![image](https://user-images.githubusercontent.com/22033488/122224253-ec919900-ce81-11eb-9f34-c786fd228dec.png)

**Desktop (please complete the following information):**
 - OS: Unraid 6.9.2
 - Browser: Firefox
 - Gaps Version: v.0.9.7

**Comment by thedoginthewok** [comment]
How was this solved? I have this issue right now.

**Comment by JasonHHouse** [comment]
@thedoginthewok When you navigate to `{ip}:8484/gaps` what do you see? This log above shows Gaps is running at the base URL of `/gaps` but the page requested was without `/gaps` just adding that will fix your issue.

**Comment by thedoginthewok** [comment]
That works! I haven't used this in a while and forgot about this.

**Comment by JasonHHouse** [comment]
>That works!

Awesome!
