### ISSUE TITLE
Movie Not Picked Up From Collection

### ISSUE THREAD

**Issue by russtyisme** [JasonHHouse/gaps#249]
**Describe the bug**
I have a few of the "Crossword Mysteries" TV movies added to Plex.  When Gaps ran through the movies and searched collections (e.g. for "Crossword Mysteries Proposing Murder"), it identified all movies, however it did not check whether "Crossword Mysteries: Riddle Me Dead" was owned (which it wasn't).

Checking the logs I can see that for every time it checked the collection for the other movies, directly under when it looked at "Crossword Mysteries: Riddle Me Dead" it couldn't parse a date:

`{"log":"2021-08-08 01:20:02.684  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : BasicMovie{name='Crossword Mysteries: Riddle Me Dead', year=2021, nameWithoutBadCharacters='Crossword Mysteries Riddle Me Dead', posterUrl='', language='en', overview='', moviesInCollection=[], ratingKey=-1, key='', imdbId='', collectionTitle='', collectionId=-1, backdropPathUrl='', tmdbId=784410, genres=[]}\n","stream":"stdout","time":"2021-08-07T15:20:02.684954634Z"}
{"log":"2021-08-08 01:20:02.685  WARN 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : Could not parse date\n","stream":"stdout","time":"2021-08-07T15:20:02.685419496Z"}`

I'm not sure if that is the cause but it is the only thing that appears different from other movies that successfully added. If that is what prevented the movie from being picked up and added to the RSS feed can you explain why/how to fix so I know what to look out for in future?

**Full Logs For Collection Search:**

`{"log":"2021-08-08 01:20:02.681  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : BasicMovie{name='Crossword Mysteries Proposing Murder', year=2019, nameWithoutBadCharacters='Crossword Mysteries Proposing Murder', posterUrl='/library/metadata/54401/thumb/1598261612', language='en', overview='When an old friend of New York Sentinel Crosswords editor Tess Harper is found murdered on the very day her puzzle includes his proposal of marriage, Tess unofficially teams up with Detective Logan O’Connor to find the killer.', moviesInCollection=[], ratingKey=54401, key='/library/metadata/54401', imdbId='tt9759888', collectionTitle='Crossword Mysteries', collectionId=659217, backdropPathUrl='', tmdbId=639254, genres=[TV Movie, Mystery]}\n","stream":"stdout","time":"2021-08-07T15:20:02.681772971Z"}
{"log":"2021-08-08 01:20:02.681  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : Used Collection ID to get Crossword Mysteries Proposing Murder\n","stream":"stdout","time":"2021-08-07T15:20:02.681820057Z"}
{"log":"2021-08-08 01:20:02.684  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : BasicMovie{name='Crossword Mysteries: A Puzzle to Die For', year=2019, nameWithoutBadCharacters='Crossword Mysteries A Puzzle to Die For', posterUrl='', language='en', overview='', moviesInCollection=[], ratingKey=-1, key='', imdbId='', collectionTitle='', collectionId=-1, backdropPathUrl='', tmdbId=529245, genres=[]}\n","stream":"stdout","time":"2021-08-07T15:20:02.684236628Z"}
{"log":"2021-08-08 01:20:02.684  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : BasicMovie{name='Crossword Mysteries: Proposing Murder', year=2019, nameWithoutBadCharacters='Crossword Mysteries Proposing Murder', posterUrl='', language='en', overview='', moviesInCollection=[], ratingKey=-1, key='', imdbId='', collectionTitle='', collectionId=-1, backdropPathUrl='', tmdbId=639254, genres=[]}\n","stream":"stdout","time":"2021-08-07T15:20:02.684439917Z"}
{"log":"2021-08-08 01:20:02.684  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : BasicMovie{name='Crossword Mysteries: Abracadaver', year=2020, nameWithoutBadCharacters='Crossword Mysteries Abracadaver', posterUrl='', language='en', overview='', moviesInCollection=[], ratingKey=-1, key='', imdbId='', collectionTitle='', collectionId=-1, backdropPathUrl='', tmdbId=639289, genres=[]}\n","stream":"stdout","time":"2021-08-07T15:20:02.684722809Z"}
{"log":"2021-08-08 01:20:02.684  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : BasicMovie{name='Crossword Mysteries: Terminal Descent', year=2021, nameWithoutBadCharacters='Crossword Mysteries Terminal Descent', posterUrl='', language='en', overview='', moviesInCollection=[], ratingKey=-1, key='', imdbId='', collectionTitle='', collectionId=-1, backdropPathUrl='', tmdbId=783508, genres=[]}\n","stream":"stdout","time":"2021-08-07T15:20:02.68484302Z"}
{"log":"2021-08-08 01:20:02.684  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : BasicMovie{name='Crossword Mysteries: Riddle Me Dead', year=2021, nameWithoutBadCharacters='Crossword Mysteries Riddle Me Dead', posterUrl='', language='en', overview='', moviesInCollection=[], ratingKey=-1, key='', imdbId='', collectionTitle='', collectionId=-1, backdropPathUrl='', tmdbId=784410, genres=[]}\n","stream":"stdout","time":"2021-08-07T15:20:02.684954634Z"}
{"log":"2021-08-08 01:20:02.685  WARN 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : Could not parse date\n","stream":"stdout","time":"2021-08-07T15:20:02.685419496Z"}
{"log":"2021-08-08 01:20:02.685  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : BasicMovie{name='Crossword Mysteries 6', year=0, nameWithoutBadCharacters='Crossword Mysteries 6', posterUrl='', language='en', overview='', moviesInCollection=[], ratingKey=-1, key='', imdbId='', collectionTitle='', collectionId=-1, backdropPathUrl='', tmdbId=784421, genres=[]}\n","stream":"stdout","time":"2021-08-07T15:20:02.685446395Z"}
{"log":"2021-08-08 01:20:02.685  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : MoviesInCollection: [MovieFromCollection{title='Crossword Mysteries: A Puzzle to Die For', tmdbId=529245, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Proposing Murder', tmdbId=639254, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Abracadaver', tmdbId=639289, owned=true, year=2020}, MovieFromCollection{title='Crossword Mysteries: Terminal Descent', tmdbId=783508, owned=true, year=2021}, MovieFromCollection{title='Crossword Mysteries: Riddle Me Dead', tmdbId=784410, owned=false, year=2021}, MovieFromCollection{title='Crossword Mysteries 6', tmdbId=784421, owned=false, year=0}]\n","stream":"stdout","time":"2021-08-07T15:20:02.685827521Z"}
{"log":"2021-08-08 01:20:02.685  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : Movie found: BasicMovie{name='Crossword Mysteries Proposing Murder', year=2019, nameWithoutBadCharacters='Crossword Mysteries Proposing Murder', posterUrl='/library/metadata/54401/thumb/1598261612', language='en', overview='When an old friend of New York Sentinel Crosswords editor Tess Harper is found murdered on the very day her puzzle includes his proposal of marriage, Tess unofficially teams up with Detective Logan O’Connor to find the killer.', moviesInCollection=[], ratingKey=54401, key='/library/metadata/54401', imdbId='tt9759888', collectionTitle='Crossword Mysteries', collectionId=659217, backdropPathUrl='', tmdbId=639254, genres=[TV Movie, Mystery]}\n","stream":"stdout","time":"2021-08-07T15:20:02.685865281Z"}
{"log":"2021-08-08 01:20:02.685  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : No poster found for Crossword Mysteries: A Puzzle to Die For.\n","stream":"stdout","time":"2021-08-07T15:20:02.685952936Z"}
{"log":"2021-08-08 01:20:02.686  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : Skip owned movie: BasicMovie{name='Crossword Mysteries: A Puzzle to Die For', year=2019, nameWithoutBadCharacters='Crossword Mysteries A Puzzle to Die For', posterUrl='', language='en', overview='', moviesInCollection=[MovieFromCollection{title='Crossword Mysteries: A Puzzle to Die For', tmdbId=529245, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Proposing Murder', tmdbId=639254, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Abracadaver', tmdbId=639289, owned=true, year=2020}, MovieFromCollection{title='Crossword Mysteries: Terminal Descent', tmdbId=783508, owned=true, year=2021}, MovieFromCollection{title='Crossword Mysteries: Riddle Me Dead', tmdbId=784410, owned=false, year=2021}, MovieFromCollection{title='Crossword Mysteries 6', tmdbId=784421, owned=false, year=0}], ratingKey=-1, key='', imdbId='', collectionTitle='Crossword Mysteries', collectionId=659217, backdropPathUrl='', tmdbId=529245, genres=[TV Movie, Mystery]}\n","stream":"stdout","time":"2021-08-07T15:20:02.686207294Z"}
{"log":"2021-08-08 01:20:02.686  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : No poster found for Crossword Mysteries: Proposing Murder.\n","stream":"stdout","time":"2021-08-07T15:20:02.68627039Z"}
{"log":"2021-08-08 01:20:02.686  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : Skip owned movie: BasicMovie{name='Crossword Mysteries: Proposing Murder', year=2019, nameWithoutBadCharacters='Crossword Mysteries Proposing Murder', posterUrl='', language='en', overview='', moviesInCollection=[MovieFromCollection{title='Crossword Mysteries: A Puzzle to Die For', tmdbId=529245, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Proposing Murder', tmdbId=639254, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Abracadaver', tmdbId=639289, owned=true, year=2020}, MovieFromCollection{title='Crossword Mysteries: Terminal Descent', tmdbId=783508, owned=true, year=2021}, MovieFromCollection{title='Crossword Mysteries: Riddle Me Dead', tmdbId=784410, owned=false, year=2021}, MovieFromCollection{title='Crossword Mysteries 6', tmdbId=784421, owned=false, year=0}], ratingKey=-1, key='', imdbId='', collectionTitle='Crossword Mysteries', collectionId=659217, backdropPathUrl='', tmdbId=639254, genres=[TV Movie, Mystery]}\n","stream":"stdout","time":"2021-08-07T15:20:02.686548811Z"}
{"log":"2021-08-08 01:20:02.686  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : No poster found for Crossword Mysteries: Abracadaver.\n","stream":"stdout","time":"2021-08-07T15:20:02.68661356Z"}
{"log":"2021-08-08 01:20:02.686  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : Skip owned movie: BasicMovie{name='Crossword Mysteries: Abracadaver', year=2020, nameWithoutBadCharacters='Crossword Mysteries Abracadaver', posterUrl='', language='en', overview='', moviesInCollection=[MovieFromCollection{title='Crossword Mysteries: A Puzzle to Die For', tmdbId=529245, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Proposing Murder', tmdbId=639254, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Abracadaver', tmdbId=639289, owned=true, year=2020}, MovieFromCollection{title='Crossword Mysteries: Terminal Descent', tmdbId=783508, owned=true, year=2021}, MovieFromCollection{title='Crossword Mysteries: Riddle Me Dead', tmdbId=784410, owned=false, year=2021}, MovieFromCollection{title='Crossword Mysteries 6', tmdbId=784421, owned=false, year=0}], ratingKey=-1, key='', imdbId='', collectionTitle='Crossword Mysteries', collectionId=659217, backdropPathUrl='', tmdbId=639289, genres=[TV Movie, Mystery]}\n","stream":"stdout","time":"2021-08-07T15:20:02.686784157Z"}
{"log":"2021-08-08 01:20:02.686  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : No poster found for Crossword Mysteries: Terminal Descent.\n","stream":"stdout","time":"2021-08-07T15:20:02.686820346Z"}
{"log":"2021-08-08 01:20:02.686  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : Skip owned movie: BasicMovie{name='Crossword Mysteries: Terminal Descent', year=2021, nameWithoutBadCharacters='Crossword Mysteries Terminal Descent', posterUrl='', language='en', overview='', moviesInCollection=[MovieFromCollection{title='Crossword Mysteries: A Puzzle to Die For', tmdbId=529245, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Proposing Murder', tmdbId=639254, owned=true, year=2019}, MovieFromCollection{title='Crossword Mysteries: Abracadaver', tmdbId=639289, owned=true, year=2020}, MovieFromCollection{title='Crossword Mysteries: Terminal Descent', tmdbId=783508, owned=true, year=2021}, MovieFromCollection{title='Crossword Mysteries: Riddle Me Dead', tmdbId=784410, owned=false, year=2021}, MovieFromCollection{title='Crossword Mysteries 6', tmdbId=784421, owned=false, year=0}], ratingKey=-1, key='', imdbId='', collectionTitle='Crossword Mysteries', collectionId=659217, backdropPathUrl='', tmdbId=783508, genres=[TV Movie, Mystery]}\n","stream":"stdout","time":"2021-08-07T15:20:02.68694062Z"}
{"log":"2021-08-08 01:20:02.686  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : No poster found for Crossword Mysteries: Riddle Me Dead.\n","stream":"stdout","time":"2021-08-07T15:20:02.686995526Z"}
{"log":"2021-08-08 01:20:02.687  INFO 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : Merging collection movie\n","stream":"stdout","time":"2021-08-07T15:20:02.687398322Z"}
{"log":"2021-08-08 01:20:02.688  WARN 8 --- [nio-8484-exec-2] c.j.gaps.service.GapsSearchService       : No year found for Crossword Mysteries 6. Value returned was empty. Not adding the movie to recommended list.\n","stream":"stdout","time":"2021-08-07T15:20:02.688836915Z"}`

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2 LTS 
 - Docker
 - Gaps v0.9.7

**Comment by JasonHHouse** [comment]
@russtyisme I'm looking into it.

**Comment by JasonHHouse** [comment]
I found the issue. Please pull the latest version of Gaps for the fix and thanks for posting the bug.
