### ISSUE TITLE
Gaps currently reports future releases as missing

### ISSUE THREAD

**Issue by m-theredhead** [JasonHHouse/gaps#257]
When I run gaps, it is suggesting movies like Avatar 2, 3, 4, and 5 which are slated to be released over the next 6 years.   

Could we exclude not yet released movies from the recommendation of gaps?   I don't see the value of having them in the report when they can't be purchased and added to your collection.

Thoughts?

**Comment by JasonHHouse** [comment]
I can make that change. The only caveat is that I would still have movies released this year based on the current code. I'm working with a release year, not a release date.

**Comment by m-theredhead** [comment]
Thanks,

That seems reasonable.    In the same year would at least be near term and something to watch for.

**Comment by seanhamlin** [comment]
I also just found these 'gaps' in my collection

![image](https://user-images.githubusercontent.com/10605846/132483362-3366b6b0-e49f-41c0-8f19-bec0be1761cd.png)

I simple approach might be

```
if movie release date > today
  skip
```

**Comment by hausner** [comment]
i would love to see this feature as well.

**Comment by Andrewpaps** [comment]
+1

**Comment by Droppisalt** [comment]
just leaving a comment to say I'd love this feature as I'm having loads of upcoming Marvel movies along with Avatar sequels

**Comment by JasonHHouse** [comment]
I'm working on a branch now. I'll push to Alpha today or tomorrow for you to test. I'll let you know when. The option right now is searching for `All` movies or only `Released` movies. This is under Settings > TMDB.

<img width="1161" alt="Screen Shot 2022-01-24 at 9 49 40 PM" src="https://user-images.githubusercontent.com/2931958/150902077-08e0f134-79d7-4bfc-8f60-e7d40ac2bfb6.png">

**Comment by JasonHHouse** [comment]
`housewrecker/gaps:alpha` is pushed. Please test out the improvement.

**Comment by Droppisalt** [comment]
After using the Advanced option "Delete All Stored Data" and after updating my library and doing a search from scratch, I'm still seeing upcoming movies (such as John Wick 4 (2023), Avatar 3 (2024), etc.). I did make sure to select the "Released" option

**Comment by JasonHHouse** [comment]
@Droppisalt This was on alpha or latest?

**Comment by Droppisalt** [comment]
Sorry for the delay. It's in the alpha version

`---
services:
  gaps:
    image: housewrecker/gaps:alpha
    container_name: gaps
    privileged: true
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=America/Toronto
    ports:
      - 8484:8484
    restart: unless-stopped
    expose:
      - "32400"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /home/pi/.config/appdata/gaps:/usr/data:Z
`

**Comment by JasonHHouse** [comment]
You don't need to delete all stored data, you can just update to "Released" and re-search. I just tested again and it's working with Avatar and John Wick and Gaps blocked them correctly for me. When I switched to all, all movies show up. I'm going to need to see your logs to know what is going on with your docker.

**Comment by m-theredhead** [comment]
I just tested and had good results.   I set it to released and rescanned.   I am no longer seeing movies like avatar, etc as missing.

**Comment by Droppisalt** [comment]
Ahh I've redone a search and it seems to be working for me now as well. I think it just didn't update to Released properly the 1st time

**Comment by Droppisalt** [comment]
Yep, not even showing Avatar 2 which still has a release date set for 2022!

**Comment by Andrewpaps** [comment]
Reporting fixed for me, excellent work.

**Comment by JasonHHouse** [comment]
Merged and pushed to `latest`.
