### ISSUE TITLE
Plex or local folders

### ISSUE THREAD

**Issue by grbharati** [JasonHHouse/gaps#267]
![image](https://user-images.githubusercontent.com/69709740/147848797-93338cf5-14e3-4f21-a6ec-cf251cbaeaf6.png)

In the readme, it is mentioned that gaps scans the plex db or local folders, but I couldn't find the way to add local folders in the setting (I use Emby). Is it a typo in the documentation or am I missing the clue here.

Thank you,

**Comment by JasonHHouse** [comment]
It's a type in the documentation. A long, long time ago Gaps supported local folders but that was when it was just a command-line app.

**Comment by grbharati** [comment]
Understood! by any chance do you plan to integrate gaps with Emby? ;-)

**Comment by JasonHHouse** [comment]
Yeah, that is on the list!
