### ISSUE TITLE
Feature: hide movies with a release date in the future

### ISSUE THREAD

**Issue by tuxpeople** [JasonHHouse/gaps#269]
**Is your feature request related to a problem? Please describe.**
As a user I want my Library to be complete. Therefore, my goal is to have a empty "missing" list. But that's no possible as long as I can see movies which are only planned but not yet released:

**Describe the solution you'd like**
I'd like to have an of/off option in settings to hide movies with a release date in the future.

**Describe alternatives you've considered**
Alternative would be an more advanced option to define a year in a textbox (or dropdown) to specify until which year gaps should display missing movies. 

**Additional context**
![image](https://user-images.githubusercontent.com/1506076/148196454-6a5987e9-7087-4d44-8f4c-3323818a4f54.png)

**Comment by JasonHHouse** [comment]
Good idea. I'll look into it.

**Comment by tuxpeople** [comment]
Sorry, looks like i missed that this is a duplicate of #257. Looks like this is an older feature request, but still desirable.

**Comment by JasonHHouse** [comment]
It is, I'll just close both when I get to them.

**Comment by Trekgater** [comment]
came in to ask if this could be added  as only actually missing are future releases.

**Comment by JasonHHouse** [comment]
`housewrecker/gaps:alpha` is pushed. Please test out the improvement.

**Comment by JasonHHouse** [comment]
Merged and pushed to `latest`.

**Comment by tuxpeople** [comment]
> `housewrecker/gaps:alpha` is pushed. Please test out the improvement.

tested now alpha (as my latest didn't have that feature yet) and it worked es expected. I highly appreciate the work you put into this!!!
