### ISSUE TITLE
version tags for docker image

### ISSUE THREAD

**Issue by tuxpeople** [JasonHHouse/gaps#272]
**Is your feature request related to a problem? Please describe.**
It is best practice to not use "latest" for deployments. At least in Kubernetes.

**Describe the solution you'd like**
I'd like to get version tags. Personally, for my containers, I do semantic versioning and use a couple of tags.

Example:
- Say I release version v1.2.3, that Image will get four tags: `latest`, `v1`, `v1.2` and `v1.2.3`
- When I later release v1.2.4, that image will take over the tags `latest`, `v1`, `v1.2` and gets additionally `v1.2.4`

Using this schema, anyone can either pin to a given patch release, a given minor-release level or a specific major release.

**Additional context**
As I can see on https://hub.docker.com/r/housewrecker/gaps/tags there have been version tags earlier, eg. `v0.8.8`

**Comment by tuxpeople** [comment]
While browsing trough https://hub.docker.com/r/housewrecker/gaps/tags for this issue, I also discovered that `v0.8.8` was a multi arch build containing arm, while current `latest` is still multiarch, but without arm. Arm is now a separate tag.  I'd like to propose to come back to a multi arch image with all archs in one image. So I don't need to change tags or search tags when using the same deployment on different archs. Do you need a separate issue for this?

**Comment by JasonHHouse** [comment]
> I'd like to get version tags.

That's fine. I can update the build script to add a version build while updating the latest. 

> While browsing trough https://hub.docker.com/r/housewrecker/gaps/tags for this issue, I also discovered that v0.8.8 was a multi arch build containing arm, while current latest is still multiarch, but without arm. Arm is now a separate tag. I'd like to propose to come back to a multi arch image with all archs in one image. So I don't need to change tags or search tags when using the same deployment on different archs. Do you need a separate issue for this?

This should be fixed now. I just pushed a new version if you want to check it out.
