### ISSUE TITLE
Gaps shows missing movies for a movie which I do not have 

### ISSUE THREAD

**Issue by tuxpeople** [JasonHHouse/gaps#287]
**Describe the bug**
In "Missing", Gaps shows me two Pokémon movies to add, because it thinks I have one from 2016
In "Library", there's no Pokémon movie
In my Plex library, there is really no Pokémon movie 

**Expected behavior**
No Pokémon movie should be showed anywhere.

**Screenshots**
In "Missing", Gaps shows me two Pokémon movies to add, because it thinks I have one:
![Bildschirmfoto 2022-01-24 um 16 34 21](https://user-images.githubusercontent.com/1506076/150815331-3d836997-2dc1-4dab-b889-10e65b7a980f.png)

In "Library", there's no Pokémon movie
![Bildschirmfoto 2022-01-24 um 16 34 41](https://user-images.githubusercontent.com/1506076/150815381-f9674c03-8fa6-4d11-9d51-905fc04adb34.png)

**Additional context**
 - Gaps Version v0.9.13 in container

**Comment by JasonHHouse** [comment]
Can you send me the logs and the generated json files showing your collections and the RSS feed? That will help me figure out what is going on.

**Comment by tuxpeople** [comment]
@JasonHHouse  Hi Jason you can grab the requested files here: https://www.dropbox.com/sh/vngg4sqhiv2yjny/AADimWqyPIfciBj70ccq-2Tna?dl=0

I'll delete them again later. Hope those are helpful. Let me know what else I can do to help.

**Comment by JasonHHouse** [comment]
It's matching on this. 

`BasicMovie{name='Wunderwerk Penis', year=2016, nameWithoutBadCharacters='Wunderwerk Penis', posterUrl='/library/metadata/4587/thumb/1641291028', language='en', overview='', moviesInCollection=[], ratingKey=4587, key='/library/metadata/4587', imdbId='', collectionTitle='Pokémon: XY Collection', collectionId=661029, backdropPathUrl='', tmdbId=382190, genres=[]}
2022-01-24 16:04:22.689  INFO 9 --- [nio-8484-exec-5] c.j.gaps.service.GapsSearchService       : `

I don't know what Wunderwerk Penis (2016) is. It seems to be a TV show, not a movie when I Google. But if you look at the results it's matching to Pokemon XY Collection. I'm not sure what the file is you're trying to match here is. Are your movie titles in Plex German by chance?

**Comment by tuxpeople** [comment]
Hmm... That's a TV documentary. Wasn't able to match it in Plex. I deleted it now, as I don't need it anyway.

Yes, they are in German. I thought Gaps would match on IMDB or TMDB ids, not on text. 

The interesting thing is, why isn't it showing up in "Library", only in "Missing"? And would it make sense to only scan the movies that are matched to something in Plex?

**Comment by JasonHHouse** [comment]
> Yes, they are in German. I thought Gaps would match on IMDB or TMDB ids, not on text.

If Plex returns an IMDB or TVDB, ID the name isn't an issue. It's only when Plex doesn't have those IDs that I need to do a search and language comes into play. 

It's unclear what the file it was matching on and how it was be interpreted. I'd need more time to dive into the issue there.

**Comment by tuxpeople** [comment]
Ok, I did a Re-Search and now the Pokémons are gone :-)

I suggest to ignore Movies that do not return an ID from Plex. Or to add a option to activate this behavior. On the other hand, most of the users probably do not have unmatched stuff in their library.

**Comment by JasonHHouse** [comment]
Yeah, it's the last chance catch if the IDs don't come back to try and match. Since it's automated it's not always going to make the be decisions. 

I'll close this out and thanks for using Gaps!
