### ISSUE TITLE
Base URL with sub directory Reverse Proxy

### ISSUE THREAD

**Issue by SteffanCline** [JasonHHouse/gaps#292]
I wrote a service file for Gaps on Ubuntu to have it controlled by systemd. It works all except for the reverse proxy. I can't seem to figure out the correct config. I saw that you worked on it back in [Feb of 2021](https://github.com/JasonHHouse/gaps/issues/193) but I am not able to get it right in the current release. Is ```baseURL``` the correct option?

Apache config
```
<Location /gaps>
    ProxyPass http://localhost:8484/gaps
    ProxyPassReverse http://localhost:8484/gaps
    Order deny,allow
    Deny from all
    Allow from all
</Location>
```

My service file is as follows
```
[Unit]
Description=Gaps
After=network-online.target

[Service]
User=gaps
Group=media
UMask=0022

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=gaps

WorkingDirectory=/opt/Gaps/
ExecStart=/usr/bin/java -jar -Dspring.profiles.active=no-ssl-no-login -Dinfo.app.baseUrl='/gaps' -Dinfo.app.storageFolder=/var/lib/gaps /opt/Gaps/gaps.jar
Type=simple
TimeoutStopSec=30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

My screen ends up looking just like it did in the issue mentioned above from Feb 2021.
<img width="474" alt="Screen Shot 2022-02-02 at 1 07 49 AM" src="https://user-images.githubusercontent.com/1323544/152116307-c3c90b49-2ba2-403d-bcae-9caf349648ab.png">

**Comment by JasonHHouse** [comment]
`-Dserver.servlet.context-path=${baseUrl} ` Is the path for the baseUrl

**Comment by SteffanCline** [comment]
This worked! I didn't see it in the docs. Thanks for the help.

For anyone else needing a service file for it, this will work. It sets up gaps to run just like all the other tools like Sonarr, Radarr and Lidarr. In my case, I have a user specific to each app and each of the apps are in the ```media``` group I created for all of the plex related apps.
```
[Unit]
Description=Gaps
After=network-online.target

[Service]
User=gaps
Group=media
UMask=0022

StandardOutput=syslog
StandardError=syslog
SyslogIdentifier=gaps

WorkingDirectory=/opt/Gaps/
ExecStart=/usr/bin/java -jar -Dspring.profiles.active=no-ssl-no-login -Dserver.servlet.context-path=/gaps -Dinfo.app.storageFolder=/var/lib/gaps /opt/Gaps/gaps.jar
Type=simple
TimeoutStopSec=30
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
```

**Comment by SteffanCline** [comment]
Additionally, for MacOS, create a file called ```org.user.gaps.plist``` in either ```~/Library/LaunchAgents``` if you run everything under one user or under ```/Library/LaunchDaemons``` if you want to run it with different privs.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
	<key>EnvironmentVariables</key>
    	<dict>
        	<key>PATH</key>
        	<string>/Library/Java/Home/bin:$PATH</string>
    	</dict>
	<key>WorkingDirectory</key>
    	<string>/Applications/GapsAsJar</string>
        <key>Label</key>
        <string>org.user.gaps.plist</string>
        <key>ProgramArguments</key>
          <array>
            <string>/usr/bin/java</string>
            <string>-Dspring.config.location=classpath:file:application-custom.yml</string>
            <string>-Dspring.profiles.active=custom</string>
            <string>-jar</string>
            <string>gaps.jar</string>
         </array>
        <key>RunAtLoad</key>
            <true/>
        <key>KeepAlive</key>
            <true/>
        <key>StandardErrorPath</key>
            <string>logs/gaps-launchd.log</string>
        <key>StandardOutPath</key>
            <string>logs/gaps-launchd.log</string>
    </dict>
</plist>
```

Then you can just use ```launchctl load ~/Library/LaunchAgents/org.user.gaps.plist``` to start gaps and have it load at boot as well.

**Comment by JasonHHouse** [comment]
Thanks for writing this up and I'm glad you got it working.

**Comment by SteffanCline** [comment]
My pleasure. If there's any other details you need, let me know.

This is actually very handy. I have a landing page on my media server and all the links are set the same way - http://myurl/gaps, http://myurl/radarr etc. Very handy!
