### ISSUE TITLE
Search for missing movies stucks at the same point

### ISSUE THREAD

**Issue by mcflym** [JasonHHouse/gaps#294]
**Describe the bug**
Searching for missing movies stucks at the same point again and again. How can I see on which movie it happens? Is there a logfile?

I already deleted all stored data and did a rescan/research. Same issue...

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Browser chrome
 - Gaps Version 0.9.10

**Comment by JasonHHouse** [comment]
There is a log file. It should be where you have the jar running. I would recommend running the latest version as well as I've made some fixes to search since then. That can be found here. https://github.com/JasonHHouse/gaps/releases/tag/v0.10.1

**Comment by mcflym** [comment]
Oh, didn't check for new version. My fault!

It's working now!

Is there something planned to check the version within the app?

**Comment by JasonHHouse** [comment]
That's a good idea. I'll look into it.
