### ISSUE TITLE
Minor UI bug

### ISSUE THREAD

**Issue by pendrgnmmj** [JasonHHouse/gaps#295]
**Describe the bug**
When you reduce the width of the browser window (in my case I snapped it to the left of my monitor) the menu disappears below a certain threshold and cannot be accessed. 

![image](https://user-images.githubusercontent.com/101308298/157585561-5e9fcfd6-f52d-414c-93b6-b1d15c26b715.png)

**Expected behavior**
I would expect the menu to collapse to a hamburger menu or something like that. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome / and Edge

**Comment by JasonHHouse** [comment]
I'll check it out.

**Comment by pendrgnmmj** [comment]
@JasonHHouse thank you!
