### ISSUE TITLE
output file compatible with radarr/couch potato

### ISSUE THREAD

**Issue by JasonHHouse** [JasonHHouse/Gaps#3]
it might be more useful to make the output file compatible with radarr/couch potato so all the movies could easily be imported

**Comment by zacharyd3** [comment]
In addition, this could be done somehow by creating an IMdb playlist with the missing movies, then the user just needs to add the playlist to radarrs "lists" feature.

**Comment by JasonHHouse** [comment]
Fixed in 0.0.3
