### ISSUE TITLE
Despite having TMDB set to 'Released', I'm still getting a list of unreleased movies

### ISSUE THREAD

**Issue by ljlongwing** [JasonHHouse/gaps#300]
v0.10.1

Lets say I have two movies in my Library.

Avatar
Scream

In my missing movies list, because there is only one released Avatar movie...Avatar 2-5 are not listed as missing....but, there have been 5 released Scream movies, and one un-released movie.

When listing Scream, it has a section for each of the Scream movies...interestingly, it has a 'space' for each of them that are released and missing....but in the bottom of each 'missing' display it gives me, it tells me the ones I own and the ones I'm missing....

It is displaying the unreleased movie in the missing section
![screenshot 182](https://user-images.githubusercontent.com/9967628/158472988-4ac96570-dda4-4267-a189-e7c28b10f738.jpg)
In this case...Scream 6 is not yet released, but still listed as missing :)

**Comment by JasonHHouse** [comment]
I don't follow what the issue is. Did you update the flag under the TMDB settings to remove unreleased movies or is this something else?

**Comment by ljlongwing** [comment]
I loaded my Plex movies, scanned for missing movies, then changed the TMDB setting from All to Released, and hit the 'Re-Search' button.  After the re-search was done, I was going through the list of movies that are missing.  In the example above, I have Scream from '96 and Scream from '22, but none of the others in my library.  It shows me 'placards' for Scream 2, 3, and 4 as 'missing'....but within each of the 2-4 placards it lists the Owned and Missing.  The problem is that Scream 6 is not yet released....and while it didn't list it in the overall list of missing movies (the 3 released movies that I don't have), it does show it in the Missing section within each.

**Comment by ljlongwing** [comment]
confirmed that I'm no longer getting the extra unexpected values
