### ISSUE TITLE
errors trying to run gaps 0.0.3.jar

### ISSUE THREAD

**Issue by notnicecream** [JasonHHouse/Gaps#34]
Hi,
I've been trying to figure out the best way to get this thing to run. So I finally just downloaded the jar and put the application.yaml in a folder together. I edited the application.yaml with my plex key and moviedb key and I'm getting these errors when I try to run the jar through powershell - https://imgur.com/a/L15wp8l

Also I'm not 100% sure my plex token thing is working, I've gotten the key from my view xml file and inserted it and tried removing the brackets in the url and leaving the brackets in the url and both gave the same errors. Then I checked the ID for my movies and it is indeed ID 1 but the url for it(http://127.0.0.1:32400/library/sections/1/all/?X-Plex-Token=) doesn't work(nothing loads when I go to the url) but I go to http://127.0.0.1:32400/library/sections/2/all/?X-Plex-Token= or http://127.0.0.1:32400/library/sections/3/all/?X-Plex-Token= which are tv shows and music and they both load just fine in my browser. 

I'm guessing that's the problem i'm getting is that the plex movie id url is incorrect maybe?

**Comment by JasonHHouse** [comment]
Try running with the docker build now.
