### ISSUE TITLE
error

### ISSUE THREAD

**Issue by thatoneguyfromit** [JasonHHouse/Gaps#42]

**Comment by thatoneguyfromit** [comment]
Any help with this, my movie url is correct and everything else seems to be working. I have around 2050 movies in my library it shows 0. Thanks in advance this seems like a nice piece of software.

**Comment by Knoxie** [comment]
When you put the MovieURL in your browser what does it show?

**Comment by thatoneguyfromit** [comment]
The xml list of movies loads up.

**Comment by Knoxie** [comment]
Were you able to figure this out?

**Comment by thatoneguyfromit** [comment]
Yes I did it was my firewall I have in place was blocking it. I second the comment of moving the    movie dB list authorization up the script. I seem to always miss the cutoff if I am not starring at it.   
  

  
  

  
  
>

**Comment by Knoxie** [comment]
It's already been moved, just not released. If you pull the dev version from the branch it'll be in the beginning.

**Comment by thatoneguyfromit** [comment]
I’ll take a look thanks for the help. Have a good one.   
  

  
  

  
  
>
