### ISSUE TITLE
Error on Configuration page

### ISSUE THREAD

**Issue by tiffaneywatts** [JasonHHouse/Gaps#55]
I have GAPS installed via docker and I am having an issue trying to bypass the configuration page... I keep getting  the attached error. 
![Screen Shot 2019-10-18 at 12 08 28 PM](https://user-images.githubusercontent.com/38788814/67110205-2c314a80-f1a0-11e9-910e-56b94bb16642.png)

**Comment by JasonHHouse** [comment]
Can you attach the browser logs if you have them? And can you try using an incognito browser window? I'll check it out as well.

**Comment by Knoxie** [comment]
Not reproducible on latest release.
