### ISSUE TITLE
Raspberry Pi Docker Compose

### ISSUE THREAD

**Issue by mouzzampk2014** [JasonHHouse/Gaps#60]
Hi, 
Can I run this docker compose on raspberry pi? 
Thank you

**Comment by JasonHHouse** [comment]
I don't see why not? I don't have a raspberry pi to test, but if you have docker then it should run just fine.

**Comment by JasonHHouse** [comment]
Added a compose file to master.

**Comment by mouzzampk2014** [comment]
Thank you its installed but I am getting these messages in the logs
```
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by JasonHHouse** [comment]
I have no idea what that means. Again, I don't have a Rasberry pi, so you're running a bit out of band. The compose file works on my mac. I don't know what OS you're evening running and what the docker support is.
