### ISSUE TITLE
How to run gaps and create TMDB list?

### ISSUE THREAD

**Issue by jt70471** [JasonHHouse/Gaps#66]
Hi, it seems you have transitioned from a command line approach to a web UI approach. That's fine of course, but how can I run as a docker container to create a TMDB list? I see that issue #25 seemingly added the ability to populate a TMDB list, however, I am unable to get that to work using the following docker run command:

```
docker run \
        --rm \
        --name gaps \
        -t \
        -e DBAPIKEY=[redacted] \
        -e PLEXADDRESS=https://[redacted]/library/sections/1/all/?X-Plex-Token=[redacted] \
        -e TMDBLISTID=[redacted] \
        -e WRITETOFILE=true \
        -p 8443:8443 \
        --expose 32400 \
        housewrecker/gaps:latest
```
Is there a way to accomplish this? The web app works OK for me, but copying the list to the clipboard seems to be my only current output option, which isn't very useful IMHO.

Thanks

**Comment by Knoxie** [comment]
Did you follow the CMD line prompts?

It will prompt you for a URL that you must go to and approve access to your TMDB.  After going to the link you go back to the CMD line and Hit enter (some terminals require several enters).

Did any of that happen for you?

**Comment by jt70471** [comment]
No, I get no command line prompts at all...

**Comment by Knoxie** [comment]
I'll have to look closer at this tomorrow. Where are you running it from ? Windows? Linux? 

You may have better luck filling in the yaml and running the jar

**Comment by jt70471** [comment]
Ubuntu 18.04, I'll try to figure out the yaml and run the jar as you suggest.

**Comment by JasonHHouse** [comment]
Which release did you pull? You need to use [v0.0.3](https://github.com/JasonHHouse/Gaps/releases/tag/0.0.3)

**Comment by jt70471** [comment]
I pulled v0.0.4, let me try v0.0.3

**Comment by jt70471** [comment]
I was able to get this to work using v0.0.3... Had to build my own docker container as you only have v0.0.4 on docker hub. Will that functionality eventually make it into a future version?

**Comment by Knoxie** [comment]
Planning to, yes.

**Comment by jt70471** [comment]
ok, i'll close this and just watch for future updates, thanks.
