### ISSUE TITLE
Feature Request - Use Radarr's "Import Exclusions" movie list for movies for Gaps to ignore

### ISSUE THREAD

**Issue by uG7D1v8Q07N** [JasonHHouse/Gaps#68]
Would it be possible to have Gaps when proposing movies that are missing from collections for it to ignore movies based off either an ignore button within gaps (to ignore a proposed movie on future rescans) ...OR... for it to ignore a movie if it sees the movie is on Radarr's excluded movie list (Import Exclusions)? 

For example, in Radarr if you go and search for a movie and you hit the "Ignore this movie, so it does not show up anymore" button (eye with a line through it) so that the movie will not be included in list pulls etc. That list of all previously ignored movies can be found under Radarr's Settings > Lists > Import Exclusions. If while your proposing missing movies from a collection you could compare the movie against that "Import Exclusions" list that would be ideal (or make this an option that can be turned on / off by user at time they run the Gaps scan). That way if there are certain movies people are intentionally deciding to ignore such as some crappy "straight to DVD" sequels then those don't keep showing up in future Gaps scan.

**Comment by JasonHHouse** [comment]
I am planning to have some persistence added to ignore movies in later scans. Radarr Import Exclusions is something we can look into as well to bring in known exclusions.

**Comment by Knoxie** [comment]
For now using the planned RSS list feature, it will abide by the import exclusion list.
