### ISSUE TITLE
Add ombi.io support 

### ISSUE THREAD

**Issue by JasonHHouse** [JasonHHouse/Gaps#7]
Hey, just saw post about GAPS, well rather your comment. I am not sure if you are familiar with ombi https://ombi.io it would be pretty cool after finding movies within the collections that are missing if there was a way to either pass all of them as requests to ombi or select specific ones to pass to ombi so that radarr can get the request and grab them. Legally of course. ;)

**Comment by JasonHHouse** [comment]
https://github.com/tidusjar/Ombi/wiki/Api-Information

**Comment by ryantrappy** [comment]
This issue as well as #3 are likely related. I have forked the repo and started the process by adding the movie Id to the movie object. I see two ways forward, automatically send the movies to the downloader without user intervention or output the data to a file and have another command to send it. What are your thoughts?

**Comment by JasonHHouse** [comment]
I'd probably start with the command to send it. That seems easier in the short term to get a solution out. Then we can work on the automated part. We have a docker file now too, so integrating that all together would be pretty cool. How's that sound?

**Comment by ryantrappy** [comment]
I haven't worked with spring much, I mostly develop android. Is there an easy way to have a different command or pass in a parameter?

**Comment by JasonHHouse** [comment]
I don't know enough about ombi.io. Is it running as a service that we can send something like a RESTful request to?

**Comment by ryantrappy** [comment]
Yeah it is a rest endpoint, it just takes in the movie db id which is why I added it to the movie object on my fork. I was more asking on how to launch the function that would loop through the file (probably) created by running Gaps to send them all to ombi. The same thing can be done with radarr and couch potato as they all have a rest endpoint that depend on the movie id.

**Comment by Knoxie** [comment]
We now support sending the suggested list by providing an RSS type feed.
