### ISSUE TITLE
Certificate Revoked

### ISSUE THREAD

**Issue by markhaines** [JasonHHouse/Gaps#76]
I'm unable to access the Gaps site using Chrome browser as it flags "Certificate Revoked" warning and won't let me proceed.  I *can* access the site by clicking through warnings using Safari and the app itself is configured and working correctly.  Cert causing the issue:

<img width="798" alt="Screenshot_14_11_2019__10_13" src="https://user-images.githubusercontent.com/1022008/68849449-00838080-06ca-11ea-97c5-7e249958753b.png">

**Comment by JasonHHouse** [comment]
Use docker pull housewrecker/gaps:latest-no-ssl
