### ISSUE TITLE
add Movie Database Api Key and Plex Token as docker ENV variables

### ISSUE THREAD

**Issue by ljmerza** [JasonHHouse/Gaps#77]
```
TMDB_API_KEY=
PLEX_TOKEN=
```

**Comment by JasonHHouse** [comment]
Gaps is expressly moving away from docker env variables to make it easier for people to use. We use cookies in the browser to persist the values already so, either way, it's only one-time entry.

**Comment by ljmerza** [comment]
Who moves away from docker? You're making all the wrong moves

**Comment by Knoxie** [comment]
You're misreading.

We moved into docker. We are moving away from environmental variables for
configuration.  The purpose of the UI is to enter that data easily and get
easy data back.  The one time entry is stored with a cookie so you don't
have to re-enter it often.  We do plan on persisting data more in the
future which will include config type data.
