### ISSUE TITLE
Use HTTP instead of HTTPS to connect

### ISSUE THREAD

**Issue by giopas** [JasonHHouse/Gaps#78]
Hi,

I am trying to test this very promising soft, thanks for your work!

Is there a way to use HTTP protocol instead of HTTPS to use Gaps? Indeed, I'd like to use a reverse proxy (Caddy) in front of it and this creates problems. It would be nice to switch HTTPS off.

How to do it?

Thanks!

**Comment by Knoxie** [comment]
The latest release has a docker build for 'no-ssl'

**Comment by JasonHHouse** [comment]
docker pull housewrecker/gaps:latest-no-ssl
