### ISSUE TITLE
Add option to ignore animated movies in collections

### ISSUE THREAD

**Issue by Duggie264** [JasonHHouse/gaps#85]
e.g. Have live action movie series, I am missing some, but because of the popularity of the series, I am inundated with animated versions - I do not want these in my collection, therefore a toggle to deselect animated movies from results would be nice.

**Comment by JasonHHouse** [comment]
I'll see what options I have in the API to add this.

**Comment by teambvd** [comment]
Possible dupe to #124 ? This one was first, but #124 would cover this as well I think?

**Comment by JasonHHouse** [comment]
I think #124 would cover this and it's next on my list as it is an improvement that will help a lot of users.

**Comment by Duggie264** [comment]
Agreed.
