### ISSUE TITLE
[Feature Request] Import into Radarr

### ISSUE THREAD

**Issue by fletchto99** [JasonHHouse/gaps#91]
Thanks for creating gaps! I'd love to be able to import individual items into radarr directly from gaps via a single button press.

**Comment by Knoxie** [comment]
I don't know that radarr supports that. Haven't explored to see if radarr
has any API support for adding individual movies or not.  Something we
could research though.

**Comment by fletchto99** [comment]
I know there's the option to import large libraries via RSS but there's 2 issues with that:

1. Large libraries might not want everything from the RSS feed
2. Radarr v3 preview doens't support lists yet (😅 not your issue though)

As for API support, Radarr should I think. [Ombi](https://github.com/tidusjar/Ombi) is able to import into Radarr via API.

**Comment by fletchto99** [comment]
Perhaps some inspiration can be drawn from this set of code in Ombi here: https://github.com/tidusjar/Ombi/blob/master/src/Ombi.Api.Radarr/RadarrApi.cs#L72-L120

**Comment by Migz93** [comment]
I agree, i'd love a button to add individual/all items that gaps has identified as missing into Radarr.
Radarr does indeed have an api, [this](https://github.com/Radarr/Radarr/wiki/API:Movie#post) post section is what you'd need.

As for Radarr V3 preview not supporting lists, not sure where that's come from? Radarr has had lists as long as i can remember, i'm on the Aphrodite branch now with 2 existing lists and just added the Gaps list which successfully added everything.

**Comment by fletchto99** [comment]
Intersting @Migz93!

![Screen Shot 2020-01-06 at 12 51 07 PM](https://user-images.githubusercontent.com/718681/71844387-3c601400-3083-11ea-880c-dbe6c9ee622b.png)


I figured it just wasn't implemented yet.

**Comment by Migz93** [comment]
Yeah you actually setup the lists within settings, then if you click that Lists tab under Movies you can view the items sourced from the list. I personally configure the lists to just automatically add, rather then have to go and manually add each entry.
Configure here:
![image](https://user-images.githubusercontent.com/33037112/71844513-376c8600-30be-11ea-8d40-17acbdb4c0c6.png)

Afterwards view here:
![image](https://user-images.githubusercontent.com/33037112/71844616-6edb3280-30be-11ea-9263-3715fa82ab2a.png)


Agree, any form of importing from within Gaps would be a nice to have.

**Comment by fletchto99** [comment]
Ah neat. Thanks! Yeah I've got some lists that were setup in v2 which transferred over.

**Comment by JasonHHouse** [comment]
We can add the post call in. That should be pretty straight forward.

**Comment by elembemedia** [comment]
Can someone help me with how I have this setup. I get an error trying to use this setting.
![Screen Shot 2020-01-18 at 8 56 03 PM](https://user-images.githubusercontent.com/1563284/72675160-05034700-3a35-11ea-9524-6f19ad3d7dd5.png)


Here's the Radarr error
Unable to connect to list: Object reference not set to an instance of an object
System.NullReferenceException: Object reference not set to an instance of an object
  at NzbDrone.Core.NetImport.RSSImport.RSSImportParser.LoadXmlDocument (NzbDrone.Core.NetImport.NetImportResponse indexerResponse) [0x00074] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\RSSImport\RSSImportParser.cs:79 
  at NzbDrone.Core.NetImport.RSSImport.RSSImportParser.ParseResponse (NzbDrone.Core.NetImport.NetImportResponse importResponse) [0x00018] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\RSSImport\RSSImportParser.cs:43 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].FetchPage (NzbDrone.Core.NetImport.NetImportRequest request, NzbDrone.Core.NetImport.IParseNetImportResponse parser) [0x00008] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:115 
  at NzbDrone.Core.NetImport.HttpNetImportBase`1[TSettings].TestConnection () [0x0000e] in C:\projects\radarr-usby1\src\NzbDrone.Core\NetImport\HttpNetImportBase.cs:151

**Comment by Migz93** [comment]
You need to add it as a StevenLu list not an RSS list.
https://github.com/JasonHHouse/Gaps/wiki/Radarr-List

**Comment by JasonHHouse** [comment]
That's correct, thanks @Migz93!

**Comment by svenvg93** [comment]
> Yeah you actually setup the lists within settings, then if you click that Lists tab under Movies you can view the items sourced from the list. I personally configure the lists to just automatically add, rather then have to go and manually add each entry.
> Configure here:
> ![image](https://user-images.githubusercontent.com/33037112/71844513-376c8600-30be-11ea-8d40-17acbdb4c0c6.png)
> 
> Afterwards view here (If you wanted to add specific items):
> ![image](https://user-images.githubusercontent.com/33037112/71844616-6edb3280-30be-11ea-9263-3715fa82ab2a.png)
> 
> Agree, any form of importing from within Gaps would be a nice to have.

How did you get the RSS working? I keep getting this error: _Certificate validation for https://192.168.1.5:8484/rss failed. RemoteCertificateNameMismatch, RemoteCertificateChainErrors_

<img width="738" alt="Screenshot 2020-02-22 at 18 13 13" src="https://user-images.githubusercontent.com/4511676/75096342-05947d80-559f-11ea-812e-cec098c4a3a4.png">

**Comment by EZarnosky** [comment]
I played with adding movies via a script. If you use the [Radarr API Movie Post](https://github.com/Radarr/Radarr/wiki/API:Movie), then it will add to Radarr.

Something I did discover was that unless you use the [Radarr API Lookup](https://github.com/Radarr/Radarr/wiki/API:Movie-Lookup) for the movie on tmdb, you will not get all the required fields. So you need to first search for the movie through Radarr, then take that info and add the movie to Radarr with the information you retrieved.

**Comment by mmaghometech** [comment]
Following the directions to a tee as you posted but, rss feed will not connect successfully.  Running in unRAID and added as a StevenLu list.

**Comment by angrycuban13** [comment]
I'm having the same issue as the person above. I added the list as a StevenLu list. I'm running it on docker with Radarr V3 and I just pulled your docker image.

**Comment by JasonHHouse** [comment]
Looks like the wiki is just outdated. I'll update. But instead of pasting in https://192.168.4.15:8484/rss go to the RSS button, click your library and copy that RSS URL in. It should look something like this http://192.168.1.8:8484/rss/c51c432ae94e316d52570550f915ecbcd71bede8/1

**Comment by angrycuban13** [comment]
Ah perfect. Thanks for the update!

**Comment by JasonHHouse** [comment]
Yup, thanks for the catch.

**Comment by ronnie138** [comment]
this is brilliant thanks

**Comment by JasonHHouse** [comment]
> this is brilliant thanks

Thanks!
