### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by Galiwyx** [JasonHHouse/Gaps#95]
Hello,

I downloaded the Windows version, installed Java then I clicked on Glaps-v0.1.2.exe, a command windows appeared. I went to http://localhost:8484/ but firefox displays "Connection failed".

I've already Homebridge on the port 8080. Is it possible to change the port of GAPS ?

Thank you.

**Comment by JasonHHouse** [comment]
Open a command window, navigate to the exe and run it. Paste in the error in the log. The exe closes to fast to show the error log.

**Comment by Galiwyx** [comment]
Hello,
I changed the port of Homebridge and it works ;)

**Comment by JasonHHouse** [comment]
Sweet
