### ISSUE TITLE
Missing Error

### ISSUE THREAD

**Issue by Galiwyx** [JasonHHouse/Gaps#96]
GAPS had some weird behaviour,  most of time, GAPS reports movies missed that I already have.

For informations, my libraries are in french.

Thank you

**Comment by JasonHHouse** [comment]
What version of Gaps? What are you running in Windows or Docker? I'll need the logs as well.

**Comment by Galiwyx** [comment]
Hello,
I run the version 0.1.2 on Windows.

For the logs : https://pastebin.com/ngkvgGre

**Comment by JasonHHouse** [comment]
There are no errors here. Gaps worked and found your missing movies.

`Time Elapsed: 218 seconds.
Times used TVDB ID: 188
2020-01-07 00:32:28.584  INFO 8548 --- [         Gaps-1] com.jasonhhouse.gaps.service.IoService   : writeRecommendedToFile()
2020-01-07 00:32:28.593  INFO 8548 --- [         Gaps-1] com.jasonhhouse.gaps.service.IoService   : writeMovieIdsToFile()`

**Comment by JasonHHouse** [comment]
Thanks, I'll check it out.

**Comment by JasonHHouse** [comment]
Can you try this version? I made a fix for you.

`docker pull housewrecker/gaps:v0.1.3`

**Comment by Galiwyx** [comment]
Hello thank you for the fix but I don't have docker ;)

**Comment by JasonHHouse** [comment]
I'll make a Windows build for you tonight.

**Comment by Galiwyx** [comment]
Thank you !

**Comment by JasonHHouse** [comment]
Can you try this release?

https://github.com/JasonHHouse/Gaps/releases/tag/v0.1.4

**Comment by Galiwyx** [comment]
Hello,

Thank your for your hard work and the release ! Unfortunately, it adds movies that I have already as missing movies.

**Comment by JasonHHouse** [comment]
Bummer! Okay, I'll keep working on it. Mind sending me the logs again.

**Comment by Galiwyx** [comment]
Sure, please find the logs below : 

https://pastebin.com/KtQ3hbBP

**Comment by JasonHHouse** [comment]
Give this a try
https://github.com/JasonHHouse/Gaps/releases/tag/v0.1.5

**Comment by Galiwyx** [comment]
Thanks you,

Unfortunately it lists the movies I already have. However, less films are returned with this version, it finds 220 films against more than 500 with the old versions of the software.

Please find logs : https://pastebin.com/80himj7K

**Comment by JasonHHouse** [comment]
I don't know that I can fix this quickly. I think the issue is two fold. One is that the search for TMDB is set to English. So any movies with foreign titles will cause duplicate issues. The second is the results returned for searching movies from TDMB aren't ordered in a very meaningful way. Sometimes it's pretty accurate, other times it's wildly out of order. To fix this, I would need a UI to handle when multiple results are returned and allow a user to select the correct match. This will take some time to implement. 

If you have your movieIds.json and recommended.json files, that would be helpful as well.

**Comment by Galiwyx** [comment]
Sorry for the logs, forgot to remove sensitive information : https://pastebin.com/7ECYWXNL

I understand, no problem. I'm sorry that I can't help you more. You can find 2 json files here : 

https://1drv.ms/u/s!AvP6rzHAfqfKi4c_FiUik9myqPj0rg?e=T3isnB
https://1drv.ms/u/s!AvP6rzHAfqfKi4c-w3-i7s6ho_jKNQ?e=4Rco3Q

**Comment by JasonHHouse** [comment]
Exactly as expected for the duplicates

`    {
        "tvdbId": 8587,
        "imdbId": "",
        "name": "The Lion King",
        "year": 1994,
        "collectionId": 94032,
        "collection": "The Lion King Collection"
    },`

`    {
        "tvdbId": 8587,
        "imdbId": "tt0110357",
        "name": "Le Roi lion",
        "year": 1994,
        "collectionId": 94032,
        "collection": "The Lion King Collection"
    },`

I'm working it though.

**Comment by JasonHHouse** [comment]
How about this one?

https://github.com/JasonHHouse/Gaps/releases/tag/v0.1.6

**Comment by Galiwyx** [comment]
Can you create the Windows version ? Thank you ;)

**Comment by JasonHHouse** [comment]
Fixed* My bad

**Comment by Galiwyx** [comment]
No problem ;)

Tested and no change with the 1.0.5 version. 

Logs and files : https://1drv.ms/u/s!AvP6rzHAfqfKi4dFZLo3RmXo_6Qs7A?e=Rzdoux

**Comment by JasonHHouse** [comment]
I added regional language support. This might make an improvement for you. Let me know.
https://github.com/JasonHHouse/Gaps/releases/tag/v0.2.0

**Comment by Galiwyx** [comment]
Hello,
Thank you, it seems resolved ! I still have 3-4 movies duplicated but it's good !

**Comment by JasonHHouse** [comment]
Awesome, so glad to hear it. I'll do a bit more testing and switch it to the mainline branch soon.
